apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lobby.fullname" . }}
  labels:
    {{- include "lobby.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "lobby.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "lobby.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lobby.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: jwt-private-key
          secret:
            secretName: {{ .Values.global.jwt.existingSecret }}
            items:
              - key: {{ .Values.global.jwt.privateKey.secretRefKey }}
                path: {{ .Values.global.jwt.privateKey.secretRefKey }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_PORT
              value: "80"
            - name: BASE_URL
              value: {{ .Values.baseUrl }}
            - name: ENABLED_FEATURES
              value: "p2p_quic,direct_tcp,ws_relay"
            {{- with .Values.global.relayUrl }}
            - name: FORCE_RELAY_URI
              value: "{{ . }}"
            {{- end }}
            - name: RELAYS_ECDSA_JWT_KEY_FILE
              value: {{ printf "%s/%s" .Values.global.jwt.privateKey.dirPath .Values.global.jwt.privateKey.secretRefKey }}
            - name: REDIS_HOST
              value: "{{ .Release.Name }}-redis-master"
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: jwt-private-key
              mountPath: {{ .Values.global.jwt.privateKey.dirPath }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
